Tickets/dm 33755
lsst-sqre/cachemachine pull request #100
Opened 2022-03-21 19:10 UTC by dspeck1

Initial commit of Google Artifact Registry support in Cache Machine.  New RepoGar class is created.  Tested running for 20 hours and was able to pull and cache new images in the development cluster.  Below is summary of changes.  

cachemachine.py modified to run RepoGar for repomen.

rubinrepogar.py is new file.  First part initiates variables for connecting to GAR.  GAR groups images together with same hash so did not include logic to construct images with matching hashes.  Moved pulling recommend image to beginning of logic since that should be pulled first.

types.py modified to create RepoGar types.

Changes not implemented.
kubernetes client in kubernetes.py uses an image pull secret.  This is not needed for GAR since the built in node service account is used for container image pull.  No harm in keeping as it is used outside of GAR.  May error out if pull secret is remove so could make conditional based on presence of pull secret variable.

Mock client testing.  Could use guidance if we should create GAR mock.

2022-03-22 00:02 UTC, cbanek requested changes

2022-03-22 00:02 UTC, cbanek commented on src/cachemachine/rubinrepogar.py
> +                    ):  # why does this only apply to alias tags?
not sure what this comment means

2022-03-22 18:41 UTC, dspeck1 commented on src/cachemachine/rubinrepogar.py
> +        ]  # added because of attribute error
Thanks.  Removed comment.

2022-03-22 18:45 UTC, dspeck1 commented on src/cachemachine/rubinrepogar.py
> +class RubinRepoGar(RepoGar):
@cbanek  Thanks.  How do you specify GAR to run instead of the rubinrepoman from cachemachine?

2022-03-22 23:06 UTC, cbanek commented on src/cachemachine/rubinrepogar.py
> +class RubinRepoGar(RepoGar):
https://github.com/lsst-sqre/cachemachine/blob/7a676f390640d080436c53e18ea3922280235dae/scripts/jupyter.json#L8 so here is where you'd edit the json to specify the body to say which strategy to use, Gar or normal.  This ends up going into https://github.com/lsst-sqre/phalanx/blob/715ae084e86b246ac8721e5bdc65d0f54ef83dd3/services/cachemachine/values-idfprod.yaml#L18 and associated places

2022-03-23 15:42 UTC, dspeck1 commented on src/cachemachine/rubinrepogar.py
> +class RubinRepoGar(RepoGar):
Thanks!  Removed extra abstract class.

2022-03-23 15:42 UTC, dspeck1 commented on src/cachemachine/cachemachine.py
> +    RepoGar,
Removed

2022-03-23 16:23 UTC, cbanek approved these changes

2022-03-23 16:40 UTC, dspeck1 commented
@cbanek  - should the GHA and tests 3.9 and 3.10 have run?

2022-03-24 15:59 UTC, dspeck1 commented
@cbanek - Sorry to bother.  Rebase and merge shows as "not enabled for this repository"

2022-04-06 19:23 UTC, merged